version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on:
      - mongo
      - redis
    restart: always
    profiles:
      - app

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - ./data:/data/db
    restart: always

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017
    restart: always

  redis:
    image: bitnami/redis
    environment:
      - REDIS_PASSWORD=password
      - REDIS_PORT_NUMBER=6381
    ports:
      - '6381:6381'
    restart: always

volumes:
  data:
